namespace OpcodeData
{
    public static partial class ZEMU
    {
        public static OpcodeEntry[,] i8080OpcodeList = new OpcodeEntry[,]
        {
           // No Prefix
           {
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x00, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 00: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x01, Name = CommandID.LXI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Value, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // 01nnnn: LXI BC, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x02, Name = CommandID.STAX, Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 02: STAX (BC), !A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x03, Name = CommandID.INX , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 03: INX BC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x04, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 04: INR B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x05, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 05: DCR B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x06, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 06nn: MVI B, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x07, Name = CommandID.RLC , Function = FunctionID.RL_A_CY, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 07: RLC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x08, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 4, Length = 1, }, // 08: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x09, Name = CommandID.DAD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), new ParamEntry(ParameterID.BC, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // 09: DAD !HL, BC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0A, Name = CommandID.LDAX, Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.BC, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 0A: LDAX !A, (BC)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0B, Name = CommandID.DCX , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 0B: DCX BC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0C, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 0C: INR C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0D, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 0D: DCR C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0E, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 0Enn: MVI C, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0F, Name = CommandID.RRC , Function = FunctionID.RR_A_CY, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 0F: RRC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x10, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 4, Length = 1, }, // 10: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x11, Name = CommandID.LXI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Value, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // 11nnnn: LXI DE, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x12, Name = CommandID.STAX, Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 12: STAX (DE), !A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x13, Name = CommandID.INX , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 13: INX DE
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x14, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 14: INR D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x15, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 15: DCR D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x16, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 16nn: MVI D, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x17, Name = CommandID.RAL , Function = FunctionID.RL_A, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 17: RAL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x18, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 4, Length = 1, }, // 18: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x19, Name = CommandID.DAD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // 19: DAD !HL, DE
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1A, Name = CommandID.LDAX, Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.DE, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 1A: LDAX !A, (DE)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1B, Name = CommandID.DCX , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 1B: DCX DE
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1C, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 1C: INR E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1D, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 1D: DCR E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1E, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 1Enn: MVI E, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1F, Name = CommandID.RAR , Function = FunctionID.RR_A, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 1F: RAR
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x20, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 4, Length = 1, }, // 20: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x21, Name = CommandID.LXI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Value, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // 21nnnn: LXI HL, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x22, Name = CommandID.SHLD, Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // 22nnnn: SHLD (nnnn), !HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x23, Name = CommandID.INX , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 23: INX HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x24, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 24: INR H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x25, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 25: DCR H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x26, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 26nn: MVI H, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x27, Name = CommandID.DAA , Function = FunctionID.BCD_ADJUST, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 27: DAA
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x28, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 4, Length = 1, }, // 28: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x29, Name = CommandID.DAD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // 29: DAD !HL, HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2A, Name = CommandID.LHLD, Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 16, Length = 3, }, // 2Annnn: LHLD !HL, (nnnn)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2B, Name = CommandID.DCX , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 2B: DCX HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2C, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 2C: INR L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2D, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 2D: DCR L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2E, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 2Enn: MVI L, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2F, Name = CommandID.CMA , Function = FunctionID.NOT, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 2F: CMA !A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x30, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 4, Length = 1, }, // 30: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x31, Name = CommandID.LXI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Value, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // 31nnnn: LXI SP, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x32, Name = CommandID.STA , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // 32nnnn: STA (nnnn), !A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x33, Name = CommandID.INX , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 33: INX SP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x34, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // 34: INR (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x35, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // 35: DCR (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x36, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 2, }, // 36nn: MVI (HL), nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x37, Name = CommandID.STC , Function = FunctionID.CY_SET, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 37: STC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x38, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 4, Length = 1, }, // 38: NOP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x39, Name = CommandID.DAD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // 39: DAD !HL, SP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3A, Name = CommandID.LDA , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 13, Length = 3, }, // 3Annnn: LDA !A, (nnnn)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3B, Name = CommandID.DCX , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 3B: DCX SP
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3C, Name = CommandID.INR , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 3C: INR A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3D, Name = CommandID.DCR , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 3D: DCR A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3E, Name = CommandID.MVI , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 3Enn: MVI A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3F, Name = CommandID.CMC , Function = FunctionID.CY_INVERT, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 3F: CMC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x40, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 40: MOV B, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x41, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 41: MOV B, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x42, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 42: MOV B, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x43, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 43: MOV B, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x44, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 44: MOV B, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x45, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 45: MOV B, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x46, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 46: MOV B, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x47, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 47: MOV B, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x48, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 48: MOV C, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x49, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 49: MOV C, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x4A, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 4A: MOV C, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x4B, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 4B: MOV C, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x4C, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 4C: MOV C, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x4D, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 4D: MOV C, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x4E, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 4E: MOV C, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x4F, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 4F: MOV C, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x50, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 50: MOV D, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x51, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 51: MOV D, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x52, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 52: MOV D, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x53, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 53: MOV D, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x54, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 54: MOV D, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x55, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 55: MOV D, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x56, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 56: MOV D, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x57, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 57: MOV D, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x58, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 58: MOV E, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x59, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 59: MOV E, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x5A, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 5A: MOV E, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x5B, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 5B: MOV E, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x5C, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 5C: MOV E, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x5D, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 5D: MOV E, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x5E, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 5E: MOV E, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x5F, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 5F: MOV E, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x60, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 60: MOV H, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x61, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 61: MOV H, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x62, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 62: MOV H, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x63, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 63: MOV H, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x64, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 64: MOV H, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x65, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 65: MOV H, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x66, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 66: MOV H, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x67, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 67: MOV H, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x68, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 68: MOV L, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x69, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 69: MOV L, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x6A, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 6A: MOV L, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x6B, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 6B: MOV L, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x6C, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 6C: MOV L, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x6D, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 6D: MOV L, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x6E, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 6E: MOV L, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x6F, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 6F: MOV L, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x70, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 70: MOV (HL), B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x71, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 71: MOV (HL), C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x72, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 72: MOV (HL), D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x73, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 73: MOV (HL), E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x74, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 74: MOV (HL), H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x75, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 75: MOV (HL), L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x76, Name = CommandID.HLT , Function = FunctionID.HALT, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 76: HLT
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x77, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 77: MOV (HL), A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x78, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 78: MOV A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x79, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 79: MOV A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x7A, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 7A: MOV A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x7B, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 7B: MOV A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x7C, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 7C: MOV A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x7D, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 7D: MOV A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x7E, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 7E: MOV A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x7F, Name = CommandID.MOV , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // 7F: MOV A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x80, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 80: ADD !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x81, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 81: ADD !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x82, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 82: ADD !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x83, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 83: ADD !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x84, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 84: ADD !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x85, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 85: ADD !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x86, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // 86: ADD !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x87, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 87: ADD !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x88, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 88: ADC !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x89, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 89: ADC !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x8A, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 8A: ADC !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x8B, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 8B: ADC !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x8C, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 8C: ADC !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x8D, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 8D: ADC !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x8E, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // 8E: ADC !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x8F, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 8F: ADC !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x90, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 90: SUB !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x91, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 91: SUB !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x92, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 92: SUB !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x93, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 93: SUB !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x94, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 94: SUB !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x95, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 95: SUB !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x96, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // 96: SUB !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x97, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 97: SUB !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x98, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 98: SBB !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x99, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 99: SBB !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x9A, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 9A: SBB !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x9B, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 9B: SBB !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x9C, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 9C: SBB !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x9D, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 9D: SBB !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x9E, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // 9E: SBB !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x9F, Name = CommandID.SBB , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 9F: SBB !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA0, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A0: ANA !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA1, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A1: ANA !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA2, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A2: ANA !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA3, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A3: ANA !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA4, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A4: ANA !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA5, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A5: ANA !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA6, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // A6: ANA !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA7, Name = CommandID.ANA , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A7: ANA !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA8, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A8: XRA !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA9, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A9: XRA !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xAA, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // AA: XRA !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xAB, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // AB: XRA !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xAC, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // AC: XRA !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xAD, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // AD: XRA !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xAE, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // AE: XRA !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xAF, Name = CommandID.XRA , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // AF: XRA !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB0, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B0: ORA !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB1, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B1: ORA !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB2, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B2: ORA !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB3, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B3: ORA !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB4, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B4: ORA !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB5, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B5: ORA !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB6, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // B6: ORA !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB7, Name = CommandID.ORA , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B7: ORA !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB8, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.B, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B8: CMP !A, B
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB9, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B9: CMP !A, C
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xBA, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.D, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // BA: CMP !A, D
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xBB, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.E, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // BB: CMP !A, E
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xBC, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.H, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // BC: CMP !A, H
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xBD, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.L, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // BD: CMP !A, L
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xBE, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // BE: CMP !A, (HL)
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xBF, Name = CommandID.CMP , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // BF: CMP !A, A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC0, Name = CommandID.RNZ , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_NZ, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // C0: RNZ !NZ
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC1, Name = CommandID.POP , Function = FunctionID.POP, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // C1: POP BC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC2, Name = CommandID.JNZ , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_NZ, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // C2nnnn: JNZ !NZ, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC3, Name = CommandID.JMP , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // C3nnnn: JMP nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC4, Name = CommandID.CNZ , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_NZ, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 3, }, // C4nnnn: CNZ !NZ, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC5, Name = CommandID.PUSH, Function = FunctionID.PUSH, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // C5: PUSH BC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC6, Name = CommandID.ADI , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // C6nn: ADI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC7, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded0, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // C7: RST 0
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC8, Name = CommandID.RZ  , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_Z, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // C8: RZ !Z
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC9, Name = CommandID.RET , Function = FunctionID.RET, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // C9: RET
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCA, Name = CommandID.JZ  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_Z, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // CAnnnn: JZ !Z, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCB, Name = CommandID.JMP , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Unofficial, Cycles = 10, Length = 3, }, // CBnnnn: JMP nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCC, Name = CommandID.CZ  , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_Z, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 3, }, // CCnnnn: CZ !Z, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCD, Name = CommandID.CALL, Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 17, Length = 3, }, // CDnnnn: CALL nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCE, Name = CommandID.ACI , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // CEnn: ACI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCF, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded1, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // CF: RST 1
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD0, Name = CommandID.RNC , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_NC, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // D0: RNC !NC
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD1, Name = CommandID.POP , Function = FunctionID.POP, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // D1: POP DE
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD2, Name = CommandID.JNC , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_NC, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // D2nnnn: JNC !NC, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD3, Name = CommandID.OUT , Function = FunctionID.OUT, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 10, Length = 2, }, // D3nn: OUT nn, !A
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD4, Name = CommandID.CNC , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_NC, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 3, }, // D4nnnn: CNC !NC, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD5, Name = CommandID.PUSH, Function = FunctionID.PUSH, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // D5: PUSH DE
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD6, Name = CommandID.SUI , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // D6nn: SUI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD7, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded2, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // D7: RST 2
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD8, Name = CommandID.RC  , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_C, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // D8: RC !CY
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD9, Name = CommandID.RET , Function = FunctionID.RET, Params = new ParamEntry[] { }, Type = OpcodeType.Unofficial, Cycles = 10, Length = 1, }, // D9: RET
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDA, Name = CommandID.JC  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_C, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // DAnnnn: JC !CY, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDB, Name = CommandID.IN  , Function = FunctionID.IN, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // DBnn: IN !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDC, Name = CommandID.CC  , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_C, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 3, }, // DCnnnn: CC !CY, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDD, Name = CommandID.CALL, Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Unofficial, Cycles = 17, Length = 3, }, // DDnnnn: CALL nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDE, Name = CommandID.SBI , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // DEnn: SBI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDF, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded3, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // DF: RST 3
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE0, Name = CommandID.RPO , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_PO, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // E0: RPO !PO
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE1, Name = CommandID.POP , Function = FunctionID.POP, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // E1: POP HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE2, Name = CommandID.JPO , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_PO, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // E2nnnn: JPO !PO, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE3, Name = CommandID.XTHL, Function = FunctionID.EX, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegisterPointer, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 18, Length = 1, }, // E3: XTHL !(SP), !HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE4, Name = CommandID.CPO , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_PO, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 17, Length = 3, }, // E4nnnn: CPO !PO, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE5, Name = CommandID.PUSH, Function = FunctionID.PUSH, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // E5: PUSH HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE6, Name = CommandID.ANI , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // E6nn: ANI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE7, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded4, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // E7: RST 4
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE8, Name = CommandID.RPE , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_PE, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // E8: RPE !PE
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE9, Name = CommandID.PCHL, Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // E9: PCHL !HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xEA, Name = CommandID.JPE , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_PE, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // EAnnnn: JPE !PE, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xEB, Name = CommandID.XCHG, Function = FunctionID.EX, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // EB: XCHG !DE, !HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xEC, Name = CommandID.CPE , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_PE, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 17, Length = 3, }, // ECnnnn: CPE !PE, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xED, Name = CommandID.CALL, Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Unofficial, Cycles = 17, Length = 3, }, // EDnnnn: CALL nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xEE, Name = CommandID.XRI , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // EEnn: XRI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xEF, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded5, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // EF: RST 5
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF0, Name = CommandID.RP  , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_P, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // F0: RP !P
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF1, Name = CommandID.POP , Function = FunctionID.POP, Params = new ParamEntry[] { new ParamEntry(ParameterID.AF, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // F1: POP AF
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF2, Name = CommandID.JP  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_P, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // F2nnnn: JP !P, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF3, Name = CommandID.DI  , Function = FunctionID.DI, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // F3: DI
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF4, Name = CommandID.CP  , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_P, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 17, Length = 3, }, // F4nnnn: CP !P, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF5, Name = CommandID.PUSH, Function = FunctionID.PUSH, Params = new ParamEntry[] { new ParamEntry(ParameterID.AF, ParameterType.WordRegisterAF, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // F5: PUSH AF
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF6, Name = CommandID.ORI , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // F6nn: ORI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF7, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded6, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // F7: RST 6
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF8, Name = CommandID.RM  , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_M, ParameterType.Flag, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // F8: RM !M
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF9, Name = CommandID.SPHL, Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, true), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, true), }, Type = OpcodeType.Official, Cycles = 5, Length = 1, }, // F9: SPHL !SP, !HL
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFA, Name = CommandID.JM  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_M, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // FAnnnn: JM !M, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFB, Name = CommandID.EI  , Function = FunctionID.EI, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // FB: EI
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFC, Name = CommandID.CM  , Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.Flag_M, ParameterType.Flag, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 17, Length = 3, }, // FCnnnn: CM !M, nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFD, Name = CommandID.CALL, Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Unofficial, Cycles = 17, Length = 3, }, // FDnnnn: CALL nnnn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFE, Name = CommandID.CPI , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, true), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // FEnn: CPI !A, nn
              new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFF, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded7, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // FF: RST 7
           },

           // 0xCB Prefix

           // 0xED Prefix

           // Index Prefix

           // Index 0xCB Prefix
        };
    }
}
