namespace OpcodeData
{
    public static partial class i8085Data
    {
        public static OpcodeEntry[] OpcodeMap = new OpcodeEntry[]
        {
                new OpcodeMapping { Opcode = 0x00000, Menmontic = "NOP", Function = FunctionID.NOP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {}, }, // 00: NOP
                new OpcodeMapping { Opcode = 0x00001, Menmontic = "LXI", Function = FunctionID.LOAD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegister}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Value, Encoding = EncodingType.WordImmidate}, }, }, // 01nnnn: LXI B, nnnn
                new OpcodeMapping { Opcode = 0x00002, Menmontic = "STAX", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegisterPointer}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 02: STAX B, |A
                new OpcodeMapping { Opcode = 0x00003, Menmontic = "INX", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegister}, }, }, // 03: INX B
                new OpcodeMapping { Opcode = 0x00004, Menmontic = "INR", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 04: INR B
                new OpcodeMapping { Opcode = 0x00005, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 05: DCR B
                new OpcodeMapping { Opcode = 0x00006, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 06nn: MVI B, nn
                new OpcodeMapping { Opcode = 0x00007, Menmontic = "RLC", Function = FunctionID.RL, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 07: RLC |A
                new OpcodeMapping { Opcode = 0x00008, Menmontic = "DSUB", Function = FunctionID.SUB, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegister, Implicit = true}, }, }, // 08: *DSUB |H, |B
                new OpcodeMapping { Opcode = 0x00009, Menmontic = "DAD", Function = FunctionID.ADD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegister}, }, }, // 09: DAD |H, B
                new OpcodeMapping { Opcode = 0x0000A, Menmontic = "LDAX", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegisterPointer}, }, }, // 0A: LDAX |A, B
                new OpcodeMapping { Opcode = 0x0000B, Menmontic = "DCX", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegister}, }, }, // 0B: DCX B
                new OpcodeMapping { Opcode = 0x0000C, Menmontic = "INR", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 0C: INR C
                new OpcodeMapping { Opcode = 0x0000D, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 0D: DCR C
                new OpcodeMapping { Opcode = 0x0000E, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 0Enn: MVI C, nn
                new OpcodeMapping { Opcode = 0x0000F, Menmontic = "RRC", Function = FunctionID.RR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 0F: RRC |A
                new OpcodeMapping { Opcode = 0x00010, Menmontic = "ARHL", Function = FunctionID.SR_SIGNED, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, }, }, // 10: *ARHL |H
                new OpcodeMapping { Opcode = 0x00011, Menmontic = "LXI", Function = FunctionID.LOAD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Value, Encoding = EncodingType.WordImmidate}, }, }, // 11nnnn: LXI D, nnnn
                new OpcodeMapping { Opcode = 0x00012, Menmontic = "STAX", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegisterPointer}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 12: STAX D, |A
                new OpcodeMapping { Opcode = 0x00013, Menmontic = "INX", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister}, }, }, // 13: INX D
                new OpcodeMapping { Opcode = 0x00014, Menmontic = "INR", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 14: INR D
                new OpcodeMapping { Opcode = 0x00015, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 15: DCR D
                new OpcodeMapping { Opcode = 0x00016, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 16nn: MVI D, nn
                new OpcodeMapping { Opcode = 0x00017, Menmontic = "RAL", Function = FunctionID.RL_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 17: RAL |A
                new OpcodeMapping { Opcode = 0x00018, Menmontic = "RDLE", Function = FunctionID.RL_CY, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister, Implicit = true}, }, }, // 18: *RDLE |D
                new OpcodeMapping { Opcode = 0x00019, Menmontic = "DAD", Function = FunctionID.ADD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister}, }, }, // 19: DAD |H, D
                new OpcodeMapping { Opcode = 0x0001A, Menmontic = "LDAX", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegisterPointer}, }, }, // 1A: LDAX |A, D
                new OpcodeMapping { Opcode = 0x0001B, Menmontic = "DCX", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister}, }, }, // 1B: DCX D
                new OpcodeMapping { Opcode = 0x0001C, Menmontic = "INR", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 1C: INR E
                new OpcodeMapping { Opcode = 0x0001D, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 1D: DCR E
                new OpcodeMapping { Opcode = 0x0001E, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 1Enn: MVI E, nn
                new OpcodeMapping { Opcode = 0x0001F, Menmontic = "RAR", Function = FunctionID.RR_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 1F: RAR |A
                new OpcodeMapping { Opcode = 0x00020, Menmontic = "RIM", Function = FunctionID.RIM, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 20: RIM |A
                new OpcodeMapping { Opcode = 0x00021, Menmontic = "LXI", Function = FunctionID.LOAD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Value, Encoding = EncodingType.WordImmidate}, }, }, // 21nnnn: LXI H, nnnn
                new OpcodeMapping { Opcode = 0x00022, Menmontic = "SHLD", Function = FunctionID.LOAD, Cycles = 5, TStates = 16, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.AddressPointer, Encoding = EncodingType.WordImmidate}, new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, }, }, // 22nnnn: SHLD nnnn, |H
                new OpcodeMapping { Opcode = 0x00023, Menmontic = "INX", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister}, }, }, // 23: INX H
                new OpcodeMapping { Opcode = 0x00024, Menmontic = "INR", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 24: INR H
                new OpcodeMapping { Opcode = 0x00025, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 25: DCR H
                new OpcodeMapping { Opcode = 0x00026, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 26nn: MVI H, nn
                new OpcodeMapping { Opcode = 0x00027, Menmontic = "DAA", Function = FunctionID.BCD_ADJUST, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 27: DAA |A
                new OpcodeMapping { Opcode = 0x00028, Menmontic = "LDHI", Function = FunctionID.ADD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 28nn: *LDHI |D, |H, nn
                new OpcodeMapping { Opcode = 0x00029, Menmontic = "DAD", Function = FunctionID.ADD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister}, }, }, // 29: DAD |H, H
                new OpcodeMapping { Opcode = 0x0002A, Menmontic = "LHLD", Function = FunctionID.LOAD, Cycles = 5, TStates = 16, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.AddressPointer, Encoding = EncodingType.WordImmidate}, }, }, // 2Annnn: LHLD |H, nnnn
                new OpcodeMapping { Opcode = 0x0002B, Menmontic = "DCX", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister}, }, }, // 2B: DCX H
                new OpcodeMapping { Opcode = 0x0002C, Menmontic = "INR", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 2C: INR L
                new OpcodeMapping { Opcode = 0x0002D, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 2D: DCR L
                new OpcodeMapping { Opcode = 0x0002E, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 2Enn: MVI L, nn
                new OpcodeMapping { Opcode = 0x0002F, Menmontic = "CMA", Function = FunctionID.NOT, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 2F: CMA |A
                new OpcodeMapping { Opcode = 0x00030, Menmontic = "SIM", Function = FunctionID.SIM, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 30: SIM |A
                new OpcodeMapping { Opcode = 0x00031, Menmontic = "LXI", Function = FunctionID.LOAD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_SP, Type = ParameterType.WordRegister}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Value, Encoding = EncodingType.WordImmidate}, }, }, // 31nnnn: LXI SP, nnnn
                new OpcodeMapping { Opcode = 0x00032, Menmontic = "STA", Function = FunctionID.LOAD, Cycles = 4, TStates = 13, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.AddressPointer, Encoding = EncodingType.WordImmidate}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // 32nnnn: STA nnnn, |A
                new OpcodeMapping { Opcode = 0x00033, Menmontic = "INX", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_SP, Type = ParameterType.WordRegister}, }, }, // 33: INX SP
                new OpcodeMapping { Opcode = 0x00034, Menmontic = "INR", Function = FunctionID.INC, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 34: INR M
                new OpcodeMapping { Opcode = 0x00035, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 35: DCR M
                new OpcodeMapping { Opcode = 0x00036, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 36nn: MVI M, nn
                new OpcodeMapping { Opcode = 0x00037, Menmontic = "STC", Function = FunctionID.CY_SET, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {}, }, // 37: STC
                new OpcodeMapping { Opcode = 0x00038, Menmontic = "LDSI", Function = FunctionID.ADD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_SP, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 38nn: *LDSI |D, |SP, nn
                new OpcodeMapping { Opcode = 0x00039, Menmontic = "DAD", Function = FunctionID.ADD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_SP, Type = ParameterType.WordRegister}, }, }, // 39: DAD |H, SP
                new OpcodeMapping { Opcode = 0x0003A, Menmontic = "LDA", Function = FunctionID.LOAD, Cycles = 4, TStates = 13, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.AddressPointer, Encoding = EncodingType.WordImmidate}, }, }, // 3Annnn: LDA |A, nnnn
                new OpcodeMapping { Opcode = 0x0003B, Menmontic = "DCX", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_SP, Type = ParameterType.WordRegister}, }, }, // 3B: DCX SP
                new OpcodeMapping { Opcode = 0x0003C, Menmontic = "INR", Function = FunctionID.INC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 3C: INR A
                new OpcodeMapping { Opcode = 0x0003D, Menmontic = "DCR", Function = FunctionID.DEC, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 3D: DCR A
                new OpcodeMapping { Opcode = 0x0003E, Menmontic = "MVI", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // 3Enn: MVI A, nn
                new OpcodeMapping { Opcode = 0x0003F, Menmontic = "CMC", Function = FunctionID.CY_INVERT, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {}, }, // 3F: CMC
                new OpcodeMapping { Opcode = 0x00040, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 40: MOV B, B
                new OpcodeMapping { Opcode = 0x00041, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 41: MOV B, C
                new OpcodeMapping { Opcode = 0x00042, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 42: MOV B, D
                new OpcodeMapping { Opcode = 0x00043, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 43: MOV B, E
                new OpcodeMapping { Opcode = 0x00044, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 44: MOV B, H
                new OpcodeMapping { Opcode = 0x00045, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 45: MOV B, L
                new OpcodeMapping { Opcode = 0x00046, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 46: MOV B, M
                new OpcodeMapping { Opcode = 0x00047, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 47: MOV B, A
                new OpcodeMapping { Opcode = 0x00048, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 48: MOV C, B
                new OpcodeMapping { Opcode = 0x00049, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 49: MOV C, C
                new OpcodeMapping { Opcode = 0x0004A, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 4A: MOV C, D
                new OpcodeMapping { Opcode = 0x0004B, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 4B: MOV C, E
                new OpcodeMapping { Opcode = 0x0004C, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 4C: MOV C, H
                new OpcodeMapping { Opcode = 0x0004D, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 4D: MOV C, L
                new OpcodeMapping { Opcode = 0x0004E, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 4E: MOV C, M
                new OpcodeMapping { Opcode = 0x0004F, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 4F: MOV C, A
                new OpcodeMapping { Opcode = 0x00050, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 50: MOV D, B
                new OpcodeMapping { Opcode = 0x00051, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 51: MOV D, C
                new OpcodeMapping { Opcode = 0x00052, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 52: MOV D, D
                new OpcodeMapping { Opcode = 0x00053, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 53: MOV D, E
                new OpcodeMapping { Opcode = 0x00054, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 54: MOV D, H
                new OpcodeMapping { Opcode = 0x00055, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 55: MOV D, L
                new OpcodeMapping { Opcode = 0x00056, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 56: MOV D, M
                new OpcodeMapping { Opcode = 0x00057, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 57: MOV D, A
                new OpcodeMapping { Opcode = 0x00058, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 58: MOV E, B
                new OpcodeMapping { Opcode = 0x00059, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 59: MOV E, C
                new OpcodeMapping { Opcode = 0x0005A, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 5A: MOV E, D
                new OpcodeMapping { Opcode = 0x0005B, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 5B: MOV E, E
                new OpcodeMapping { Opcode = 0x0005C, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 5C: MOV E, H
                new OpcodeMapping { Opcode = 0x0005D, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 5D: MOV E, L
                new OpcodeMapping { Opcode = 0x0005E, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 5E: MOV E, M
                new OpcodeMapping { Opcode = 0x0005F, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 5F: MOV E, A
                new OpcodeMapping { Opcode = 0x00060, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 60: MOV H, B
                new OpcodeMapping { Opcode = 0x00061, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 61: MOV H, C
                new OpcodeMapping { Opcode = 0x00062, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 62: MOV H, D
                new OpcodeMapping { Opcode = 0x00063, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 63: MOV H, E
                new OpcodeMapping { Opcode = 0x00064, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 64: MOV H, H
                new OpcodeMapping { Opcode = 0x00065, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 65: MOV H, L
                new OpcodeMapping { Opcode = 0x00066, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 66: MOV H, M
                new OpcodeMapping { Opcode = 0x00067, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 67: MOV H, A
                new OpcodeMapping { Opcode = 0x00068, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 68: MOV L, B
                new OpcodeMapping { Opcode = 0x00069, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 69: MOV L, C
                new OpcodeMapping { Opcode = 0x0006A, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 6A: MOV L, D
                new OpcodeMapping { Opcode = 0x0006B, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 6B: MOV L, E
                new OpcodeMapping { Opcode = 0x0006C, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 6C: MOV L, H
                new OpcodeMapping { Opcode = 0x0006D, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 6D: MOV L, L
                new OpcodeMapping { Opcode = 0x0006E, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 6E: MOV L, M
                new OpcodeMapping { Opcode = 0x0006F, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 6F: MOV L, A
                new OpcodeMapping { Opcode = 0x00070, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 70: MOV M, B
                new OpcodeMapping { Opcode = 0x00071, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 71: MOV M, C
                new OpcodeMapping { Opcode = 0x00072, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 72: MOV M, D
                new OpcodeMapping { Opcode = 0x00073, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 73: MOV M, E
                new OpcodeMapping { Opcode = 0x00074, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 74: MOV M, H
                new OpcodeMapping { Opcode = 0x00075, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 75: MOV M, L
                new OpcodeMapping { Opcode = 0x00076, Menmontic = "HLT", Function = FunctionID.HALT, Cycles = 1, TStates = 7, Arguments = new ParamEntry[] {}, }, // 76: HLT
                new OpcodeMapping { Opcode = 0x00077, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 77: MOV M, A
                new OpcodeMapping { Opcode = 0x00078, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 78: MOV A, B
                new OpcodeMapping { Opcode = 0x00079, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 79: MOV A, C
                new OpcodeMapping { Opcode = 0x0007A, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 7A: MOV A, D
                new OpcodeMapping { Opcode = 0x0007B, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 7B: MOV A, E
                new OpcodeMapping { Opcode = 0x0007C, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 7C: MOV A, H
                new OpcodeMapping { Opcode = 0x0007D, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 7D: MOV A, L
                new OpcodeMapping { Opcode = 0x0007E, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 7E: MOV A, M
                new OpcodeMapping { Opcode = 0x0007F, Menmontic = "MOV", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 7F: MOV A, A
                new OpcodeMapping { Opcode = 0x00080, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 80: ADD |A, B
                new OpcodeMapping { Opcode = 0x00081, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 81: ADD |A, C
                new OpcodeMapping { Opcode = 0x00082, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 82: ADD |A, D
                new OpcodeMapping { Opcode = 0x00083, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 83: ADD |A, E
                new OpcodeMapping { Opcode = 0x00084, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 84: ADD |A, H
                new OpcodeMapping { Opcode = 0x00085, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 85: ADD |A, L
                new OpcodeMapping { Opcode = 0x00086, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 86: ADD |A, M
                new OpcodeMapping { Opcode = 0x00087, Menmontic = "ADD", Function = FunctionID.ADD, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 87: ADD |A, A
                new OpcodeMapping { Opcode = 0x00088, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 88: ADC |A, B
                new OpcodeMapping { Opcode = 0x00089, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 89: ADC |A, C
                new OpcodeMapping { Opcode = 0x0008A, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 8A: ADC |A, D
                new OpcodeMapping { Opcode = 0x0008B, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 8B: ADC |A, E
                new OpcodeMapping { Opcode = 0x0008C, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 8C: ADC |A, H
                new OpcodeMapping { Opcode = 0x0008D, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 8D: ADC |A, L
                new OpcodeMapping { Opcode = 0x0008E, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 8E: ADC |A, M
                new OpcodeMapping { Opcode = 0x0008F, Menmontic = "ADC", Function = FunctionID.ADD_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 8F: ADC |A, A
                new OpcodeMapping { Opcode = 0x00090, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 90: SUB |A, B
                new OpcodeMapping { Opcode = 0x00091, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 91: SUB |A, C
                new OpcodeMapping { Opcode = 0x00092, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 92: SUB |A, D
                new OpcodeMapping { Opcode = 0x00093, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 93: SUB |A, E
                new OpcodeMapping { Opcode = 0x00094, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 94: SUB |A, H
                new OpcodeMapping { Opcode = 0x00095, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 95: SUB |A, L
                new OpcodeMapping { Opcode = 0x00096, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 96: SUB |A, M
                new OpcodeMapping { Opcode = 0x00097, Menmontic = "SUB", Function = FunctionID.SUB, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 97: SUB |A, A
                new OpcodeMapping { Opcode = 0x00098, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // 98: SBB |A, B
                new OpcodeMapping { Opcode = 0x00099, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // 99: SBB |A, C
                new OpcodeMapping { Opcode = 0x0009A, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // 9A: SBB |A, D
                new OpcodeMapping { Opcode = 0x0009B, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // 9B: SBB |A, E
                new OpcodeMapping { Opcode = 0x0009C, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // 9C: SBB |A, H
                new OpcodeMapping { Opcode = 0x0009D, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // 9D: SBB |A, L
                new OpcodeMapping { Opcode = 0x0009E, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // 9E: SBB |A, M
                new OpcodeMapping { Opcode = 0x0009F, Menmontic = "SBB", Function = FunctionID.SUB_CY, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // 9F: SBB |A, A
                new OpcodeMapping { Opcode = 0x000A0, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // A0: ANA |A, B
                new OpcodeMapping { Opcode = 0x000A1, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // A1: ANA |A, C
                new OpcodeMapping { Opcode = 0x000A2, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // A2: ANA |A, D
                new OpcodeMapping { Opcode = 0x000A3, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // A3: ANA |A, E
                new OpcodeMapping { Opcode = 0x000A4, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // A4: ANA |A, H
                new OpcodeMapping { Opcode = 0x000A5, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // A5: ANA |A, L
                new OpcodeMapping { Opcode = 0x000A6, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // A6: ANA |A, M
                new OpcodeMapping { Opcode = 0x000A7, Menmontic = "ANA", Function = FunctionID.AND, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // A7: ANA |A, A
                new OpcodeMapping { Opcode = 0x000A8, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // A8: XRA |A, B
                new OpcodeMapping { Opcode = 0x000A9, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // A9: XRA |A, C
                new OpcodeMapping { Opcode = 0x000AA, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // AA: XRA |A, D
                new OpcodeMapping { Opcode = 0x000AB, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // AB: XRA |A, E
                new OpcodeMapping { Opcode = 0x000AC, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // AC: XRA |A, H
                new OpcodeMapping { Opcode = 0x000AD, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // AD: XRA |A, L
                new OpcodeMapping { Opcode = 0x000AE, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // AE: XRA |A, M
                new OpcodeMapping { Opcode = 0x000AF, Menmontic = "XRA", Function = FunctionID.XOR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // AF: XRA |A, A
                new OpcodeMapping { Opcode = 0x000B0, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // B0: ORA |A, B
                new OpcodeMapping { Opcode = 0x000B1, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // B1: ORA |A, C
                new OpcodeMapping { Opcode = 0x000B2, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // B2: ORA |A, D
                new OpcodeMapping { Opcode = 0x000B3, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // B3: ORA |A, E
                new OpcodeMapping { Opcode = 0x000B4, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // B4: ORA |A, H
                new OpcodeMapping { Opcode = 0x000B5, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // B5: ORA |A, L
                new OpcodeMapping { Opcode = 0x000B6, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // B6: ORA |A, M
                new OpcodeMapping { Opcode = 0x000B7, Menmontic = "ORA", Function = FunctionID.OR, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // B7: ORA |A, A
                new OpcodeMapping { Opcode = 0x000B8, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_B, Type = ParameterType.ByteRegister}, }, }, // B8: CMP |A, B
                new OpcodeMapping { Opcode = 0x000B9, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_C, Type = ParameterType.ByteRegister}, }, }, // B9: CMP |A, C
                new OpcodeMapping { Opcode = 0x000BA, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_D, Type = ParameterType.ByteRegister}, }, }, // BA: CMP |A, D
                new OpcodeMapping { Opcode = 0x000BB, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_E, Type = ParameterType.ByteRegister}, }, }, // BB: CMP |A, E
                new OpcodeMapping { Opcode = 0x000BC, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_H, Type = ParameterType.ByteRegister}, }, }, // BC: CMP |A, H
                new OpcodeMapping { Opcode = 0x000BD, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_L, Type = ParameterType.ByteRegister}, }, }, // BD: CMP |A, L
                new OpcodeMapping { Opcode = 0x000BE, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_M, Type = ParameterType.ByteRegister}, }, }, // BE: CMP |A, M
                new OpcodeMapping { Opcode = 0x000BF, Menmontic = "CMP", Function = FunctionID.CMP, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister}, }, }, // BF: CMP |A, A
                new OpcodeMapping { Opcode = 0x000C0, Menmontic = "RNZ", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_NZ, Type = ParameterType.Flag, Implicit = true}, }, }, // C0: RNZ |NZ
                new OpcodeMapping { Opcode = 0x000C1, Menmontic = "POP", Function = FunctionID.POP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegister}, }, }, // C1: POP B
                new OpcodeMapping { Opcode = 0x000C2, Menmontic = "JNZ", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_NZ, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // C2nnnn: JNZ |NZ, nnnn
                new OpcodeMapping { Opcode = 0x000C3, Menmontic = "JMP", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // C3nnnn: JMP nnnn
                new OpcodeMapping { Opcode = 0x000C4, Menmontic = "CNZ", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_NZ, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // C4nnnn: CNZ |NZ, nnnn
                new OpcodeMapping { Opcode = 0x000C5, Menmontic = "PUSH", Function = FunctionID.PUSH, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_BC, Type = ParameterType.WordRegister}, }, }, // C5: PUSH B
                new OpcodeMapping { Opcode = 0x000C6, Menmontic = "ADI", Function = FunctionID.ADD, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // C6nn: ADI |A, nn
                new OpcodeMapping { Opcode = 0x000C7, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value0, Type = ParameterType.Value}, }, }, // C7: RST 0
                new OpcodeMapping { Opcode = 0x000C8, Menmontic = "RZ", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_Z, Type = ParameterType.Flag, Implicit = true}, }, }, // C8: RZ |Z
                new OpcodeMapping { Opcode = 0x000C9, Menmontic = "RET", Function = FunctionID.RET, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {}, }, // C9: RET
                new OpcodeMapping { Opcode = 0x000CA, Menmontic = "JZ", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_Z, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // CAnnnn: JZ |Z, nnnn
                new OpcodeMapping { Opcode = 0x000CB, Menmontic = "RSTV", Function = FunctionID.RST, Cycles = 4, TStates = 12, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value8, Type = ParameterType.Value, Implicit = true}, }, }, // CB: *RSTV |Value8
                new OpcodeMapping { Opcode = 0x000CC, Menmontic = "CZ", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_Z, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // CCnnnn: CZ |Z, nnnn
                new OpcodeMapping { Opcode = 0x000CD, Menmontic = "CALL", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // CDnnnn: CALL nnnn
                new OpcodeMapping { Opcode = 0x000CE, Menmontic = "ACI", Function = FunctionID.ADD_CY, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // CEnn: ACI |A, nn
                new OpcodeMapping { Opcode = 0x000CF, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value1, Type = ParameterType.Value}, }, }, // CF: RST 1
                new OpcodeMapping { Opcode = 0x000D0, Menmontic = "RNC", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_NC, Type = ParameterType.Flag, Implicit = true}, }, }, // D0: RNC |NC
                new OpcodeMapping { Opcode = 0x000D1, Menmontic = "POP", Function = FunctionID.POP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister}, }, }, // D1: POP D
                new OpcodeMapping { Opcode = 0x000D2, Menmontic = "JNC", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_NC, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // D2nnnn: JNC |NC, nnnn
                new OpcodeMapping { Opcode = 0x000D3, Menmontic = "OUT", Function = FunctionID.OUT, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, }, }, // D3nn: OUT nn, |A
                new OpcodeMapping { Opcode = 0x000D4, Menmontic = "CNC", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_NC, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // D4nnnn: CNC |NC, nnnn
                new OpcodeMapping { Opcode = 0x000D5, Menmontic = "PUSH", Function = FunctionID.PUSH, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister}, }, }, // D5: PUSH D
                new OpcodeMapping { Opcode = 0x000D6, Menmontic = "SUI", Function = FunctionID.SUB, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // D6nn: SUI |A, nn
                new OpcodeMapping { Opcode = 0x000D7, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value2, Type = ParameterType.Value}, }, }, // D7: RST 2
                new OpcodeMapping { Opcode = 0x000D8, Menmontic = "RC", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_CY, Type = ParameterType.Flag, Implicit = true}, }, }, // D8: RC |CY
                new OpcodeMapping { Opcode = 0x000D9, Menmontic = "SHLX", Function = FunctionID.LOAD, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, }, }, // D9: *SHLX |D, |H
                new OpcodeMapping { Opcode = 0x000DA, Menmontic = "JC", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_CY, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // DAnnnn: JC |CY, nnnn
                new OpcodeMapping { Opcode = 0x000DB, Menmontic = "IN", Function = FunctionID.IN, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // DBnn: IN |A, nn
                new OpcodeMapping { Opcode = 0x000DC, Menmontic = "CC", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_CY, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // DCnnnn: CC |CY, nnnn
                new OpcodeMapping { Opcode = 0x000DD, Menmontic = "JNK", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_NK, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // DDnnnn: *JNK |NK, nnnn
                new OpcodeMapping { Opcode = 0x000DE, Menmontic = "SBI", Function = FunctionID.SUB_CY, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // DEnn: SBI |A, nn
                new OpcodeMapping { Opcode = 0x000DF, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value3, Type = ParameterType.Value}, }, }, // DF: RST 3
                new OpcodeMapping { Opcode = 0x000E0, Menmontic = "RPO", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_PO, Type = ParameterType.Flag, Implicit = true}, }, }, // E0: RPO |PO
                new OpcodeMapping { Opcode = 0x000E1, Menmontic = "POP", Function = FunctionID.POP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister}, }, }, // E1: POP H
                new OpcodeMapping { Opcode = 0x000E2, Menmontic = "JPO", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_PO, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // E2nnnn: JPO |PO, nnnn
                new OpcodeMapping { Opcode = 0x000E3, Menmontic = "XTHL", Function = FunctionID.EX, Cycles = 5, TStates = 18, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_SP, Type = ParameterType.WordRegisterPointer, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, }, }, // E3: XTHL |(SP), |H
                new OpcodeMapping { Opcode = 0x000E4, Menmontic = "CPO", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_PO, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // E4nnnn: CPO |PO, nnnn
                new OpcodeMapping { Opcode = 0x000E5, Menmontic = "PUSH", Function = FunctionID.PUSH, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister}, }, }, // E5: PUSH H
                new OpcodeMapping { Opcode = 0x000E6, Menmontic = "ANI", Function = FunctionID.AND, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // E6nn: ANI |A, nn
                new OpcodeMapping { Opcode = 0x000E7, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value4, Type = ParameterType.Value}, }, }, // E7: RST 4
                new OpcodeMapping { Opcode = 0x000E8, Menmontic = "RPE", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_PE, Type = ParameterType.Flag, Implicit = true}, }, }, // E8: RPE |PE
                new OpcodeMapping { Opcode = 0x000E9, Menmontic = "PCHL", Function = FunctionID.JMP, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, }, }, // E9: PCHL |H
                new OpcodeMapping { Opcode = 0x000EA, Menmontic = "JPE", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_PE, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // EAnnnn: JPE |PE, nnnn
                new OpcodeMapping { Opcode = 0x000EB, Menmontic = "XCHG", Function = FunctionID.EX, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, }, }, // EB: XCHG |D, |H
                new OpcodeMapping { Opcode = 0x000EC, Menmontic = "CPE", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_PE, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // ECnnnn: CPE |PE, nnnn
                new OpcodeMapping { Opcode = 0x000ED, Menmontic = "LHLX", Function = FunctionID.LOAD, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_DE, Type = ParameterType.WordRegister, Implicit = true}, }, }, // ED: *LHLX |H, |D
                new OpcodeMapping { Opcode = 0x000EE, Menmontic = "XRI", Function = FunctionID.XOR, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // EEnn: XRI |A, nn
                new OpcodeMapping { Opcode = 0x000EF, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value5, Type = ParameterType.Value}, }, }, // EF: RST 5
                new OpcodeMapping { Opcode = 0x000F0, Menmontic = "RP", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_P, Type = ParameterType.Flag, Implicit = true}, }, }, // F0: RP |P
                new OpcodeMapping { Opcode = 0x000F1, Menmontic = "POP", Function = FunctionID.POP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_PSW, Type = ParameterType.WordRegister}, }, }, // F1: POP PSW
                new OpcodeMapping { Opcode = 0x000F2, Menmontic = "JP", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_P, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // F2nnnn: JP |P, nnnn
                new OpcodeMapping { Opcode = 0x000F3, Menmontic = "DI", Function = FunctionID.DI, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {}, }, // F3: DI
                new OpcodeMapping { Opcode = 0x000F4, Menmontic = "CP", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_P, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // F4nnnn: CP |P, nnnn
                new OpcodeMapping { Opcode = 0x000F5, Menmontic = "PUSH", Function = FunctionID.PUSH, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_PSW, Type = ParameterType.WordRegister}, }, }, // F5: PUSH PSW
                new OpcodeMapping { Opcode = 0x000F6, Menmontic = "ORI", Function = FunctionID.OR, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // F6nn: ORI |A, nn
                new OpcodeMapping { Opcode = 0x000F7, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value6, Type = ParameterType.Value}, }, }, // F7: RST 6
                new OpcodeMapping { Opcode = 0x000F8, Menmontic = "RM", Function = FunctionID.RET, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_M, Type = ParameterType.Flag, Implicit = true}, }, }, // F8: RM |M
                new OpcodeMapping { Opcode = 0x000F9, Menmontic = "SPHL", Function = FunctionID.LOAD, Cycles = 1, TStates = 5, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.WordReg_SP, Type = ParameterType.WordRegister, Implicit = true}, new ParamEntry { Param = ParameterID.WordReg_HL, Type = ParameterType.WordRegister, Implicit = true}, }, }, // F9: SPHL |SP, |H
                new OpcodeMapping { Opcode = 0x000FA, Menmontic = "JM", Function = FunctionID.JMP, Cycles = 3, TStates = 10, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_M, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // FAnnnn: JM |M, nnnn
                new OpcodeMapping { Opcode = 0x000FB, Menmontic = "EI", Function = FunctionID.EI, Cycles = 1, TStates = 4, Arguments = new ParamEntry[] {}, }, // FB: EI
                new OpcodeMapping { Opcode = 0x000FC, Menmontic = "CM", Function = FunctionID.CALL, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_M, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // FCnnnn: CM |M, nnnn
                new OpcodeMapping { Opcode = 0x000FD, Menmontic = "JK", Function = FunctionID.JMP, Cycles = 5, TStates = 17, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Flag_K, Type = ParameterType.Flag, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateWord, Type = ParameterType.Address, Encoding = EncodingType.WordImmidate}, }, }, // FDnnnn: *JK |K, nnnn
                new OpcodeMapping { Opcode = 0x000FE, Menmontic = "CPI", Function = FunctionID.CMP, Cycles = 2, TStates = 7, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.ByteReg_A, Type = ParameterType.ByteRegister, Implicit = true}, new ParamEntry { Param = ParameterID.ImmediateByte, Type = ParameterType.Value, Encoding = EncodingType.ByteImmidate}, }, }, // FEnn: CPI |A, nn
                new OpcodeMapping { Opcode = 0x000FF, Menmontic = "RST", Function = FunctionID.RST, Cycles = 3, TStates = 11, Arguments = new ParamEntry[] {new ParamEntry { Param = ParameterID.Value7, Type = ParameterType.Value}, }, }, // FF: RST 7
        };
    }
}
