namespace OpcodeData
{
    public static partial class ZASM
    {
        public static OpcodeEntry[] z80OpcodeList = new OpcodeEntry[]
        {
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x88, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 88: ADC A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x8E, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 8E: ADC A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCE, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // CEnn: ADC A, nn
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x4A, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegister, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // ED4A: ADC HL, rr
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x88, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xx88: ADC A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x8E, Name = CommandID.ADC , Function = FunctionID.ADD_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xx8Eoo: ADC A, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x09, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegister, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // 09: ADD HL, rr
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x80, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 80: ADD A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x86, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 86: ADD A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC6, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // C6nn: ADD A, nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x09, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegister, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // xx09: ADD XX, rr
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x29, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // xx29: ADD XX, XX
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x80, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xx80: ADD A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x86, Name = CommandID.ADD , Function = FunctionID.ADD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xx86oo: ADD A, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA0, Name = CommandID.AND , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A0: AND A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA6, Name = CommandID.AND , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // A6: AND A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE6, Name = CommandID.AND , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // E6nn: AND A, nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xA0, Name = CommandID.AND , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xxA0: AND A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xA6, Name = CommandID.AND , Function = FunctionID.AND, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xxA6oo: AND A, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x40, Name = CommandID.BIT , Function = FunctionID.BIT, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB40: BIT e, r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x46, Name = CommandID.BIT , Function = FunctionID.BIT, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 12, Length = 2, }, // CB46: BIT e, (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x40, Name = CommandID.BIT , Function = FunctionID.BIT, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo40: BIT e, (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x46, Name = CommandID.BIT , Function = FunctionID.BIT, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // xxCBoo46: BIT e, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC4, Name = CommandID.CALL, Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.FlagsAny, ParameterType.Flag, EncodingType.Pos2, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 17, Length = 3, }, // C4nnnn: CALL ff, nnnn
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xCD, Name = CommandID.CALL, Function = FunctionID.CALL, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 17, Length = 3, }, // CDnnnn: CALL nnnn
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3F, Name = CommandID.CCF , Function = FunctionID.CY_INVERT, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 3F: CCF
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB8, Name = CommandID.CP  , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B8: CP A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xBE, Name = CommandID.CP  , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // BE: CP A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFE, Name = CommandID.CP  , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // FEnn: CP A, nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xB8, Name = CommandID.CP  , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xxB8: CP A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xBE, Name = CommandID.CP  , Function = FunctionID.CMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xxBEoo: CP A, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xA9, Name = CommandID.CPD , Function = FunctionID.CMP_D, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDA9: CPD
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xB9, Name = CommandID.CPDR, Function = FunctionID.CMP_DR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDB9: CPDR
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xA1, Name = CommandID.CPI , Function = FunctionID.CMP_I, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDA1: CPI
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xB1, Name = CommandID.CPIR, Function = FunctionID.CMP_IR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDB1: CPIR
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2F, Name = CommandID.CPL , Function = FunctionID.NOT, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 2F: CPL A
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x27, Name = CommandID.DAA , Function = FunctionID.BCD_ADJUST, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 27: DAA
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x05, Name = CommandID.DEC , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 05: DEC r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0B, Name = CommandID.DEC , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegister, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // 0B: DEC rr
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x35, Name = CommandID.DEC , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // 35: DEC (HL)
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x05, Name = CommandID.DEC , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos2, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xx05: DEC xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x2B, Name = CommandID.DEC , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 2, }, // xx2B: DEC XX
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x35, Name = CommandID.DEC , Function = FunctionID.DEC, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 3, }, // xx35oo: DEC (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF3, Name = CommandID.DI  , Function = FunctionID.DI, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // F3: DI
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x10, Name = CommandID.DJNZ, Function = FunctionID.DJNZ, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateByte, ParameterType.Displacment, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 13, Length = 2, }, // 10nn: DJNZ e-2
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xFB, Name = CommandID.EI  , Function = FunctionID.EI, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // FB: EI
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x08, Name = CommandID.EX  , Function = FunctionID.EX, Params = new ParamEntry[] { new ParamEntry(ParameterID.AF, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.AF_Alt, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 08: EX AF, AF'
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE3, Name = CommandID.EX  , Function = FunctionID.EX, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 1, }, // E3: EX (SP), HL
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xEB, Name = CommandID.EX  , Function = FunctionID.EX, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // EB: EX DE, HL
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xE3, Name = CommandID.EX  , Function = FunctionID.EX, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 2, }, // xxE3: EX (SP), XX
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD9, Name = CommandID.EXX , Function = FunctionID.EXX, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // D9: EXX
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x76, Name = CommandID.HALT, Function = FunctionID.HALT, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 76: HALT
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x46, Name = CommandID.IM  , Function = FunctionID.IM, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded0, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // ED46: IM 0
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x56, Name = CommandID.IM  , Function = FunctionID.IM, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded1, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // ED56: IM 1
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x5E, Name = CommandID.IM  , Function = FunctionID.IM, Params = new ParamEntry[] { new ParamEntry(ParameterID.Encoded2, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // ED5E: IM 2
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDB, Name = CommandID.IN  , Function = FunctionID.IN, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 2, }, // DBnn: IN A, nn
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x40, Name = CommandID.IN  , Function = FunctionID.IN, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 12, Length = 2, }, // ED40: IN r, C
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x70, Name = CommandID.IN  , Function = FunctionID.IN, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // ED70: IN C
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x03, Name = CommandID.INC , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegister, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // 03: INC rr
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x04, Name = CommandID.INC , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 04: INC r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x34, Name = CommandID.INC , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // 34: INC (HL)
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x04, Name = CommandID.INC , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos2, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xx04: INC xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x23, Name = CommandID.INC , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 2, }, // xx23: INC XX
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x34, Name = CommandID.INC , Function = FunctionID.INC, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 3, }, // xx34oo: INC (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xAA, Name = CommandID.IND , Function = FunctionID.IN_D, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDAA: IND
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xBA, Name = CommandID.INDR, Function = FunctionID.IN_DR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDBA: INDR
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xA2, Name = CommandID.INI , Function = FunctionID.IN_I, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDA2: INI
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xB2, Name = CommandID.INIR, Function = FunctionID.IN_IR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDB2: INIR
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC2, Name = CommandID.JP  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.FlagsAny, ParameterType.Flag, EncodingType.Pos2, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // C2nnnn: JP ff, nnnn
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC3, Name = CommandID.JP  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.Address, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // C3nnnn: JP nnnn
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xE9, Name = CommandID.JP  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // E9: JP HL
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xE9, Name = CommandID.JP  , Function = FunctionID.JMP, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // xxE9: JP XX
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x18, Name = CommandID.JR  , Function = FunctionID.JR, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateByte, ParameterType.Displacment, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 12, Length = 2, }, // 18nn: JR e-2
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x20, Name = CommandID.JR  , Function = FunctionID.JR, Params = new ParamEntry[] { new ParamEntry(ParameterID.FlagsAny, ParameterType.HalfFlag, EncodingType.Pos4, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Displacment, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 12, Length = 2, }, // 20nn: JR ff, e-2
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x01, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegister, EncodingType.Pos3, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Value, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 3, }, // 01nnnn: LD rr, nnnn
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x02, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 02: LD (BC), A
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x06, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // 06nn: LD r, nn
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0A, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.BC, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 0A: LD A, (BC)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x12, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 12: LD (DE), A
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1A, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.DE, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 1A: LD A, (DE)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x22, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 16, Length = 3, }, // 22nnnn: LD (nnnn), HL
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x2A, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 16, Length = 3, }, // 2Annnn: LD HL, (nnnn)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x32, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 13, Length = 3, }, // 32nnnn: LD (nnnn), A
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x36, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 2, }, // 36nn: LD (HL), nn
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x3A, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 13, Length = 3, }, // 3Annnn: LD A, (nnnn)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x40, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 40: LD r, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x46, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 46: LD r, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x70, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 70: LD (HL), r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF9, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 1, }, // F9: LD SP, HL
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x43, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.BC, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // ED43nnnn: LD (nnnn), BC
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x47, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.I, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 9, Length = 2, }, // ED47: LD I, A
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x4B, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.BC, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // ED4Bnnnn: LD BC, (nnnn)
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x4F, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.R, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 9, Length = 2, }, // ED4F: LD R, A
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x53, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // ED53nnnn: LD (nnnn), DE
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x57, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.I, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 9, Length = 2, }, // ED57: LD A, I
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x5B, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.DE, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // ED5Bnnnn: LD DE, (nnnn)
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x5F, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.R, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 9, Length = 2, }, // ED5F: LD A, R
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x73, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // ED73nnnn: LD (nnnn), SP
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x7B, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // ED7Bnnnn: LD SP, (nnnn)
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x06, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos2, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 3, }, // xx06nn: LD xxx, nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x21, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.Value, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 14, Length = 4, }, // xx21nnnn: LD XX, nnnn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x22, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // xx22nnnn: LD (nnnn), XX
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x2A, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateWord, ParameterType.AddressPointer, EncodingType.WordImmidate, false), }, Type = OpcodeType.Official, Cycles = 20, Length = 4, }, // xx2Annnn: LD XX, (nnnn)
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x36, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 4, }, // xx36oonn: LD (XX + oo), nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x40, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos2, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xx40: LD xxx, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x46, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xx46oo: LD r, (XX + oo)
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x70, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xx70oo: LD (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xF9, Name = CommandID.LD  , Function = FunctionID.LD, Params = new ParamEntry[] { new ParamEntry(ParameterID.SP, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 2, }, // xxF9: LD SP, XX
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xA8, Name = CommandID.LDD , Function = FunctionID.LD_D, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDA8: LDD
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xB8, Name = CommandID.LDDR, Function = FunctionID.LD_DR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDB8: LDDR
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xA0, Name = CommandID.LDI , Function = FunctionID.LD_I, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDA0: LDI
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xB0, Name = CommandID.LDIR, Function = FunctionID.LD_IR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDB0: LDIR
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x44, Name = CommandID.NEG , Function = FunctionID.NEG, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // ED44: NEG A
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x00, Name = CommandID.NOP , Function = FunctionID.NOP, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 00: NOP
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB0, Name = CommandID.OR  , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // B0: OR A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xB6, Name = CommandID.OR  , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // B6: OR A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xF6, Name = CommandID.OR  , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // F6nn: OR A, nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xB0, Name = CommandID.OR  , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xxB0: OR A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xB6, Name = CommandID.OR  , Function = FunctionID.OR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xxB6oo: OR A, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xBB, Name = CommandID.OTDR, Function = FunctionID.OUT_DR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDBB: OTDR
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xB3, Name = CommandID.OTIR, Function = FunctionID.OUT_IR, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 21, Length = 2, }, // EDB3: OTIR
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD3, Name = CommandID.OUT , Function = FunctionID.OUT, Params = new ParamEntry[] { new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 2, }, // D3nn: OUT nn, A
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x41, Name = CommandID.OUT , Function = FunctionID.OUT, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos2, false), }, Type = OpcodeType.Official, Cycles = 12, Length = 2, }, // ED41: OUT C, r
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x71, Name = CommandID.OUT , Function = FunctionID.OUT, Params = new ParamEntry[] { new ParamEntry(ParameterID.C, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.Encoded0, ParameterType.Value, EncodingType.None, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // ED71: OUT C, 0
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xAB, Name = CommandID.OUTD, Function = FunctionID.OUT_D, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDAB: OUTD
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0xA3, Name = CommandID.OUTI, Function = FunctionID.OUT_I, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 16, Length = 2, }, // EDA3: OUTI
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC1, Name = CommandID.POP , Function = FunctionID.POP, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegisterAF, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // C1: POP rr
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xE1, Name = CommandID.POP , Function = FunctionID.POP, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 14, Length = 2, }, // xxE1: POP XX
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC5, Name = CommandID.PUSH, Function = FunctionID.PUSH, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegisterAF, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // C5: PUSH rr
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xE5, Name = CommandID.PUSH, Function = FunctionID.PUSH, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegister, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // xxE5: PUSH XX
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x80, Name = CommandID.RES , Function = FunctionID.RES, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB80: RES e, r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x86, Name = CommandID.RES , Function = FunctionID.RES, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 2, }, // CB86: RES e, (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x80, Name = CommandID.RES , Function = FunctionID.RES, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo80: RES e, (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x86, Name = CommandID.RES , Function = FunctionID.RES, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 6, Length = 4, }, // xxCBoo86: RES e, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC0, Name = CommandID.RET , Function = FunctionID.RET, Params = new ParamEntry[] { new ParamEntry(ParameterID.FlagsAny, ParameterType.Flag, EncodingType.Pos2, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // C0: RET ff
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC9, Name = CommandID.RET , Function = FunctionID.RET, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 10, Length = 1, }, // C9: RET
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x4D, Name = CommandID.RETI, Function = FunctionID.RETI, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 14, Length = 2, }, // ED4D: RETI
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x45, Name = CommandID.RETN, Function = FunctionID.RETN, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 14, Length = 2, }, // ED45: RETN
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x10, Name = CommandID.RL  , Function = FunctionID.RL, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB10: RL r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x16, Name = CommandID.RL  , Function = FunctionID.RL, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CB16: RL (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x10, Name = CommandID.RL  , Function = FunctionID.RL, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo10: RL (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x16, Name = CommandID.RL  , Function = FunctionID.RL, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 4, }, // xxCBoo16: RL (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x17, Name = CommandID.RLA , Function = FunctionID.RL_A, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 17: RLA
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x00, Name = CommandID.RLC , Function = FunctionID.RL_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB00: RLC r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x06, Name = CommandID.RLC , Function = FunctionID.RL_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CB06: RLC (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x00, Name = CommandID.RLC , Function = FunctionID.RL_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo00: RLC (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x06, Name = CommandID.RLC , Function = FunctionID.RL_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 4, }, // xxCBoo06: RLC (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x07, Name = CommandID.RLCA, Function = FunctionID.RL_A_CY, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 07: RLCA
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x6F, Name = CommandID.RLD , Function = FunctionID.ROLL_L, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 19, Length = 2, }, // ED6F: RLD
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x18, Name = CommandID.RR  , Function = FunctionID.RR, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB18: RR r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x1E, Name = CommandID.RR  , Function = FunctionID.RR, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CB1E: RR (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x18, Name = CommandID.RR  , Function = FunctionID.RR, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo18: RR (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x1E, Name = CommandID.RR  , Function = FunctionID.RR, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 4, }, // xxCBoo1E: RR (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x1F, Name = CommandID.RRA , Function = FunctionID.RR_A, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 1F: RRA
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x08, Name = CommandID.RRC , Function = FunctionID.RR_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB08: RRC r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x0E, Name = CommandID.RRC , Function = FunctionID.RR_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CB0E: RRC (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x08, Name = CommandID.RRC , Function = FunctionID.RR_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo08: RRC (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x0E, Name = CommandID.RRC , Function = FunctionID.RR_CY, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 4, }, // xxCBoo0E: RRC (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x0F, Name = CommandID.RRCA, Function = FunctionID.RR_A_CY, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 0F: RRCA
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x67, Name = CommandID.RRD , Function = FunctionID.ROLL_R, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 18, Length = 2, }, // ED67: RRD
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xC7, Name = CommandID.RST , Function = FunctionID.RST, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), }, Type = OpcodeType.Official, Cycles = 11, Length = 1, }, // C7: RST e
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x98, Name = CommandID.SBC , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 98: SBC A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x9E, Name = CommandID.SBC , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 9E: SBC A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xDE, Name = CommandID.SBC , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // DEnn: SBC A, nn
            new OpcodeEntry { Index = false, Prefix = 0xED, Encoding = 0x42, Name = CommandID.SBC , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.WordRegister, EncodingType.Pos3, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // ED42: SBC HL, rr
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x98, Name = CommandID.SBC , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xx98: SBC A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x9E, Name = CommandID.SBC , Function = FunctionID.SUB_C, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xx9Eoo: SBC A, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x37, Name = CommandID.SCF , Function = FunctionID.CY_SET, Params = new ParamEntry[] { }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 37: SCF
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0xC0, Name = CommandID.SET , Function = FunctionID.SET, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CBC0: SET e, r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0xC6, Name = CommandID.SET , Function = FunctionID.SET, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CBC6: SET e, (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0xC0, Name = CommandID.SET , Function = FunctionID.SET, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBooC0: SET e, (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0xC6, Name = CommandID.SET , Function = FunctionID.SET, Params = new ParamEntry[] { new ParamEntry(ParameterID.EncodedByte, ParameterType.Value, EncodingType.Pos2, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 23, Length = 4, }, // xxCBooC6: SET e, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x20, Name = CommandID.SLA , Function = FunctionID.SL_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB20: SLA r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x26, Name = CommandID.SLA , Function = FunctionID.SL_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CB26: SLA (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x20, Name = CommandID.SLA , Function = FunctionID.SL_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo20: SLA (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x26, Name = CommandID.SLA , Function = FunctionID.SL_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 22, Length = 4, }, // xxCBoo26: SLA (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x30, Name = CommandID.SLL , Function = FunctionID.SL_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 8, Length = 2, }, // CB30: SLL r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x36, Name = CommandID.SLL , Function = FunctionID.SL_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Undocumented, Cycles = 15, Length = 2, }, // CB36: SLL (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x30, Name = CommandID.SLL , Function = FunctionID.SL_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo30: SLL (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x36, Name = CommandID.SLL , Function = FunctionID.SL_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Undocumented, Cycles = 22, Length = 4, }, // xxCBoo36: SLL (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x28, Name = CommandID.SRA , Function = FunctionID.SR_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB28: SRA r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x2E, Name = CommandID.SRA , Function = FunctionID.SR_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CB2E: SRA (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x28, Name = CommandID.SRA , Function = FunctionID.SR_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo28: SRA (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x2E, Name = CommandID.SRA , Function = FunctionID.SR_SIGNED, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 22, Length = 4, }, // xxCBoo2E: SRA (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x38, Name = CommandID.SRL , Function = FunctionID.SR_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 8, Length = 2, }, // CB38: SRL r
            new OpcodeEntry { Index = false, Prefix = 0xCB, Encoding = 0x3E, Name = CommandID.SRL , Function = FunctionID.SR_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 15, Length = 2, }, // CB3E: SRL (HL)
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x38, Name = CommandID.SRL , Function = FunctionID.SR_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 4, }, // xxCBoo38: SRL (XX + oo), r
            new OpcodeEntry { Index =  true, Prefix = 0xCB, Encoding = 0x3E, Name = CommandID.SRL , Function = FunctionID.SR_L, Params = new ParamEntry[] { new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 22, Length = 4, }, // xxCBoo3E: SRL (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x90, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // 90: SUB A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0x96, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // 96: SUB A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xD6, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // D6nn: SUB A, nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x90, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xx90: SUB A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0x96, Name = CommandID.SUB , Function = FunctionID.SUB, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xx96oo: SUB A, (XX + oo)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xA8, Name = CommandID.XOR , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Official, Cycles = 4, Length = 1, }, // A8: XOR A, r
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xAE, Name = CommandID.XOR , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.HL, ParameterType.WordRegisterPointer, EncodingType.None, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 1, }, // AE: XOR A, (HL)
            new OpcodeEntry { Index = false, Prefix = 0x00, Encoding = 0xEE, Name = CommandID.XOR , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.ImmediateByte, ParameterType.Value, EncodingType.ByteImmidate, false), }, Type = OpcodeType.Official, Cycles = 7, Length = 2, }, // EEnn: XOR A, nn
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xA8, Name = CommandID.XOR , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.RegisterAny, ParameterType.ByteIndexRegister, EncodingType.Pos1, false), }, Type = OpcodeType.Undocumented, Cycles = 0, Length = 2, }, // xxA8: XOR A, xxx
            new OpcodeEntry { Index =  true, Prefix = 0x00, Encoding = 0xAE, Name = CommandID.XOR , Function = FunctionID.XOR, Params = new ParamEntry[] { new ParamEntry(ParameterID.A, ParameterType.ByteRegister, EncodingType.None, false), new ParamEntry(ParameterID.XX, ParameterType.WordIndexRegisterPointer, EncodingType.IndexOffset, false), }, Type = OpcodeType.Official, Cycles = 19, Length = 3, }, // xxAEoo: XOR A, (XX + oo)
        };
    }
}
